---
title: "2025년 06월 01일 문제지"
format: pdf
mainfont: "NanumGothic"
fontsize: 11pt
papersize: a4
geometry: top=0.5in, bottom=0.5in, left=0.5in, right=0.5in
documentclass: article
classoption: twocolumn
linestretch: 1.3
header-includes:
  - \setlength{\columnsep}{25pt}
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)
```

### \[개념원리\] 소인수분해 p.26 - 예제 1

60에 가장 작은 자연수 $x$를 곱하여 어떤 자연수 $y$의 제곱이 되도록 할 때, $x + y$의 값을 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.26 - 예제 2

432의 약수의 개수와 $2^4 \times 3 \times 5^a$의 약수의 개수가 같을 때, 자연수 $a$의 값을 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.26 - 유제 1

44에 가장 작은 자연수 $x$를 곱하여 어떤 자연수 $y$의 제곱이 되도록 할 때, $y - x$의 값을 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.26 - 유제 2

360의 약수의 개수와 $2^2 \times 3^a \times 11$의 약수의 개수가 같을 때, 자연수 $a$의 값을 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.27 - 유제 3

자연수 400에 대하여 다음 물음에 답하시오. \[총 6점\] (1) 소인수분해 하시오. \[2점\] (2) 소인수를 모두 구하시오. \[1점\] (3) 소인수분해 한 결과를 이용하여 약수를 모두 구하시오. \[3점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.27 - 유제 4

다음 조건을 만족시키는 세 자연수 $a$, $b$, $c$에 대하여 $a - b + c$의 값을 구하시오. \[7점\]

(가) $a$는 30 미만의 자연수 중에서 가장 큰 합성수이다. (나) $b$는 260의 모든 소인수의 합이다. (다) $c$는 405의 약수의 개수이다.

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.27 - 유제 3

두 자연수 216과 $2^3 \times \square \times 5$의 최대공약수가 72일 때, $\square$ 안에 들어갈 수 있는 가장 작은 자연수와 그때의 두 수의 최소공배수를 차례대로 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.27 - 유제 4

1000의 약수 중에서 어떤 자연수의 제곱이 되는 수의 개수를 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.46 - 예제 1

세 자연수 $5 \times x$, $6 \times x$, $8 \times x$의 최소공배수가 360일 때, 세 자연수의 최대공약수를 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.46 - 예제 2

두 분수 $\dfrac{7}{15}$, $\dfrac{35}{48}$의 어느 것에 곱해도 그 결과가 자연수가 되도록 하는 가장 작은 기약분수를 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.46 - 유제 1

세 자연수 $3 \times x$, $4 \times x$, $6 \times x$의 최소공배수가 120일 때, 세 자연수 중 가장 큰 수를 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 소인수분해 p.46 - 유제 2

세 분수 $\dfrac{21}{16}$, $\dfrac{35}{54}$, $\dfrac{49}{108}$의 어느 것에 곱해도 그 결과가 자연수가 되도록 하는 가장 작은 기약분수를 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 정수와 유리수 p.66 - 예제 1

수직선 위에서 두 수 $a$, $b$를 나타내는 두 점 사이의 거리가 8이고 두 점의 한가운데에 있는 점이 나타내는 수가 3일 때, $a$, $b$의 값을 구하시오. (단, $a > b$)

\vspace{13\baselineskip}

### \[개념원리\] 정수와 유리수 p.66 - 예제 2

두 유리수 $\frac{16}{5}$과 $\frac{11}{4}$ 사이에 있는 정수 중에서 절댓값이 가장 큰 수를 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.66 - 유제 1

수직선 위에서 두 수를 나타내는 두 점 사이의 거리가 10이고 두 점의 한가운데에 있는 점이 나타내는 수가 $-1$일 때, 두 수 중 작은 수를 구하시오. \[7점\]

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.66 - 유제 2

두 유리수 $-\frac{7}{3}$과 $\frac{8}{5}$ 사이에 있는 정수 중에서 절댓값이 가장 큰 수를 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.67 - 예제 3

다음 수 중 양수의 개수를 $a$, 음수의 개수를 $b$, 정수가 아닌 유리수의 개수를 $c$라 할 때, $a + b + c$의 값을 구하시오. $$ -3,\ \frac{3}{11},\ -4.5,\ 0,\ \frac{29}{4},\ 0.9,\ 25,\ -\frac{1}{5} $$

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.67 - 예제 4

다음 조건을 만족시키는 $a$, $b$의 값을 구하시오.\
(가) $a$와 $b$의 절댓값은 같다.\
(나) 두 수 $a$, $b$를 수직선 위에 점으로 나타냈을 때의 두 점 사이의 거리는 12이다.\
(다) $|a| = a$

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.67 - 유제 3

$-\frac{10}{3}$보다 작은 수 중에서 가장 큰 정수를 $a$, $\frac{9}{2}$보다 큰 수 중에서 가장 작은 정수를 $b$라 할 때, $|a| + |b|$의 값을 구하시오.

\vspace{13\baselineskip}

### \[개념원리\] 정수와유리수 p.67 - 유제 4

(1) "$x$는 $-5$보다 작지 않고 $2$보다 크지 않다."를 부등호를 사용하여 나타내시오.\
(2) (1)을 만족시키는 정수 $x$의 개수를 구하시오.

\vspace{13\baselineskip}

### \[개념원리\] 최소공배수최대공약수 p.47 - 유제 3

두 자연수 216과 $2^3 \times \square \times 5$의 최대공약수가 72일 때, $\square$ 안에 들어갈 수 있는 가장 작은 자연수와 그때의 두 수의 최소공배수를 차례대로 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 최소공배수최대공약수 p.47 - 유제 4

두 자연수 $2^2 \times 3^2$, $A$의 최대공약수가 $2^2 \times 3$이고 최소공배수가 $2^4 \times 3^2$일 때, $A$의 약수의 개수를 구하시오. \[6점\]

\vspace{13\baselineskip}

### \[개념원리\] 최소공배수최대공약수 p.47 - 유제 6

두 자리 자연수 $A$, $B$에 대하여 $A$, $B$의 곱이 640이고 최대공약수가 8일 때, $A + B$의 값을 구하시오. \[7점\]

\vspace{13\baselineskip}
